[package]
name = "message_signing_example"
version = "0.1.0"
edition = "2021"

[dependencies]
neo3 = { path = "../.." }
tokio = { version = "1.0", features = ["full"] }
chrono = "0.4"
rand = "0.8"
hex = "0.4"