[package]
name = "neo3"
version = "0.1.3"
edition = "2021"
description = "The Neo Rust SDK for interacting with the Neo N3 blockchain"
repository = "https://github.com/RustForNeo/neo-sdk"
license = "MIT"
readme = "README.md"

[lib]
name = "neo"
path = "src/lib.rs"

[dependencies]
# Essential dependencies
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
primitive-types = { version = "0.13.0", features = ["std", "rustc-hex", "serde"] }
rustc-hex = "2.1.0"
byte-slice-cast = "1.2.2"
rustc-serialize = "0.3.24"
bs58 = "0.5.0"
base64 = "0.21.5"
sha2 = { version = "0.10.8", optional = true }
num-bigint = "0.4.4"
num-traits = "0.2.17"
rand = "0.8.5"
chrono = "0.4.31"
derive_more = "0.99.17"
strum = "0.26.1"
strum_macros = "0.26.1"
getset = "0.1.2"
hex = "0.4.3"
thiserror = "1.0.56"
log = "0.4.20"
crypto = { version = "0.5.1", optional = true, features = ["digest"] }
p256 = { version = "0.13.2", optional = true }
elliptic-curve = { version = "0.13.8", optional = true }
signature = { version = "2.2.0", optional = true }
rand_core = { version = "0.6.4", optional = true }
tokio = { version = "1.36.0", features = ["full"], optional = true }
reqwest = { version = "0.11.24", optional = true, default-features = false, features = ["json"] }
digest = { version = "0.10.7", optional = true }
ripemd160 = { version = "0.10.0", optional = true }
ripemd = { version = "0.1.3", optional = true }
hmac = { version = "0.12.1", optional = true }
lazy_static = "1.4.0"

[features]
default = ["std", "crypto-standard"]
std = ["serde/std", "serde_json/std", "primitive-types/std"]
crypto-standard = ["crypto", "p256", "elliptic-curve", "signature", "rand_core", "tokio", "reqwest", "digest", "sha2", "ripemd", "hmac"]
digest = ["dep:digest"]
sha2 = ["dep:sha2"]
ripemd160 = ["dep:ripemd160"]
nightly = []
ledger = [] # Feature for ledger hardware wallet integration
ethereum-compat = [] # Feature for Ethereum compatibility and Neo X integration
wallet = [] # Feature for wallet management functions
transaction = [] # Feature for transaction creation and signing

[dev-dependencies]
hex-literal = "0.4.1"        