[toolchain]
channel = "nightly"
components = [
    "cargo",
    "clippy",
    "rust-analyzer",
    "rust-src",
    "rust-std",
    "rustc-dev",
    "rustc",
    "rustfmt",
]
targets = ["wasm32-wasip1"]
profile = "minimal"