[package]
name = "neo_sgx_examples"
version = "0.1.0"
edition = "2021"


[features]
default = []
futures = ["neo3/futures"]
ledger = ["neo3/ledger"]
aws = ["neo3/aws"]
[dependencies]
neo3 = { path = "../../", package = "neo3", features = [] }
tokio = { version = "1.0", features = ["full"] }
sgx_types = "=1.1.1"
sgx_urts = "=1.1.1"

[[example]]
name = "sgx_wallet"
path = "examples/sgx_wallet.rs"

[[example]]
name = "sgx_rpc_client"
path = "examples/sgx_rpc_client.rs"
