[features]
default = []
futures = ["neo3/futures"]
ledger = ["neo3/ledger"]
aws = ["neo3/aws"]
[package]
name = "examples-wallets"
version = "0.0.0"
publish = false
edition = "2021"
authors = ["R3E Network <contact@r3e.network>"]

[dev-dependencies]
neo3 = { path = "../../", package = "neo3", features = [] }
tokio = { version = "1.36.0", features = ["macros", "rt-multi-thread"] }
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
eyre = "0.6.5"
[dependencies]
yubihsm = { version = "0.42", features = ["mockhsm", "http", "usb"] }
tokio = { version = "1.0.0", features = ["rt", "rt-multi-thread", "macros"] }
bip39 = { version = "2.0.0", features = ["rand"] }
rand = "0.8.0"