[build]
  base = "website/"
  publish = "public/"
  command = "npm run build:static"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/404/"
  status = 404