name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2023-12-28
          target: wasm32-wasi
          override: true
          components: rustfmt, clippy
      
      - name: Build
        run: cargo build --verbose
        
      - name: Run tests
        run: cargo test --verbose
