name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy
      
      - name: Build with all features
        run: cargo build --verbose --no-default-features --features "futures,ledger,aws,sgx,sgx_deps"
        
      - name: Build without default features
        run: cargo build --verbose --no-default-features
        
      - name: Run tests with all compatible features
        run: cargo test --features "futures,ledger,aws,sgx" --no-fail-fast -- --nocapture
        
      - name: Test examples
        run: |
          echo "Testing examples..."
          chmod +x scripts/test_examples.sh
          ./scripts/test_examples.sh
