[package]
name = "neo_crypto"
version = "0.1.0"
edition = "2021"

[dependencies]
neo3 = { path = "../.." }
hex = "0.4.3"
p256 = "0.13.2"
rand = "0.8.5"
tokio = { version = "1.32", features = ["full"] }
log = "0.4.14"
env_logger = "0.11.3"
scrypt = "0.11.0"
sha2 = "0.10.7"
base58 = "0.2.0"