[package]
name = "test-hash"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
primitive-types = "0.13.0"
crypto = { package = "rust-crypto", version = "0.2.36" }
hex = "0.4.3"
